"""empty message

Revision ID: 345c13bc94d6
Revises: 
Create Date: 2020-05-14 21:22:17.224806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345c13bc94d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(),
                                    nullable=False, server_default='False'))
    op.alter_column('user', 'confirmed', server_default=None)
    op.add_column('user', sa.Column(
        'confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed_on')
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
