"""empty message

Revision ID: 3cd4cef8b602
Revises: 345c13bc94d6
Create Date: 2020-05-15 13:45:35.492558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd4cef8b602'
down_revision = '345c13bc94d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'id')
    op.drop_column('category', 'id')
    # ### end Alembic commands ###
