"""empty message

Revision ID: 4df44c94d49e
Revises: b1f2c8aa016f
Create Date: 2020-06-10 15:54:27.515261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df44c94d49e'
down_revision = 'b1f2c8aa016f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('exp_answer', sa.Integer(), nullable=False))
    op.drop_column('answer', 'epx_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('epx_answer', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('answer', 'exp_answer')
    # ### end Alembic commands ###
