"""empty message

Revision ID: 835c7b53d427
Revises: b5839c00f61e
Create Date: 2020-06-27 15:56:33.884860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835c7b53d427'
down_revision = 'b5839c00f61e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about')
    # ### end Alembic commands ###
