"""empty message

Revision ID: ae9eee8f92b3
Revises: 3cd4cef8b602
Create Date: 2020-05-15 13:55:40.328060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9eee8f92b3'
down_revision = '3cd4cef8b602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('explanation', sa.Text(), nullable=True))
    op.alter_column('questions', 'explanation',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'explanation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('category', 'explanation')
    # ### end Alembic commands ###
