"""empty message

Revision ID: b5839c00f61e
Revises: 5b4f04e1d9ac
Create Date: 2020-06-27 14:19:11.940823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5839c00f61e'
down_revision = '5b4f04e1d9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('external_link', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('looking_for', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'looking_for')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'external_link')
    # ### end Alembic commands ###
