"""empty message

Revision ID: ddca244e5fde
Revises: 835c7b53d427
Create Date: 2020-06-29 21:51:16.339133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddca244e5fde'
down_revision = '835c7b53d427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('show_gender', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('show_looking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'show_looking')
    op.drop_column('user', 'show_gender')
    # ### end Alembic commands ###
