"""empty message

Revision ID: edc596434b9d
Revises: 4df44c94d49e
Create Date: 2020-06-10 16:06:26.512121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc596434b9d'
down_revision = '4df44c94d49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('date_posted', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'date_posted')
    # ### end Alembic commands ###
