"""empty message

Revision ID: f593c426db3b
Revises: 545824215779
Create Date: 2020-06-10 18:18:42.414684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f593c426db3b'
down_revision = '545824215779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('categories', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'categories')
    # ### end Alembic commands ###
