"""empty message

Revision ID: fe9815fe4133
Revises: d61b0b472a77
Create Date: 2020-07-13 15:05:54.676965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9815fe4133'
down_revision = 'd61b0b472a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relationships', 'master_description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('relationships', 'slave_description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relationships', 'slave_description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('relationships', 'master_description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
